import type { Metadata } from "next";
import LegalLayout from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Privacy Policy | APKI",
  description:
    "How APK Industries Ltd collects, uses, and protects information submitted through this website.",
};

export default function PrivacyPolicyPage() {
  return (
    <LegalLayout eyebrow="Legal" title="Privacy Policy" updated="3 July 2026">
      <h2>Who we are</h2>
      <p>
        This website is operated by APK Industries Ltd (&ldquo;APKI&rdquo;,
        &ldquo;we&rdquo;, &ldquo;us&rdquo;), a company registered in England and
        Wales, company number 07071667, registered office at Sparkhouse, Rope
        Walk, Lincoln LN6 7DQ, United Kingdom.
      </p>
      <p>
        This site is a business-to-business (B2B) resource for distribution
        network operators, NGOs, defence and government procurement teams,
        healthcare providers, emergency services, and other organisations
        evaluating APKI&apos;s Portable Power Stations. It is not directed at
        consumers and we do not knowingly collect personal data from children.
      </p>

      <h2>Information we collect</h2>
      <p>
        We collect only the information you choose to give us. This is
        principally:
      </p>
      <ul>
        <li>
          Business contact details submitted through our enquiry form —
          name, organisation, email address, phone number, and the content of
          your message.
        </li>
        <li>
          Correspondence you send us directly by email.
        </li>
        <li>
          Standard technical information generated by visiting the site
          (such as browser type and IP address), collected automatically by
          our hosting provider as part of normal server operation.
        </li>
      </ul>
      <p>
        We do not currently use analytics, advertising, or tracking cookies.
        See our <a href="/cookies">Cookie Policy</a> for details.
      </p>

      <h2>How we use it</h2>
      <p>
        We use the information you submit to respond to your enquiry, assess
        deployment or procurement requirements, and maintain a record of our
        business correspondence. Our legal basis for this is our legitimate
        interest in operating our business and responding to enquiries from
        organisations we deal with, and, where relevant, your consent in
        submitting the form.
      </p>

      <h2>Sharing your information</h2>
      <p>
        We do not sell or rent your information. We may share it with service
        providers who process it on our behalf (for example, our email or
        website hosting provider), or where required by law or to protect our
        legal rights. We do not transfer personal data outside the UK/EEA as
        part of normal operation of this site.
      </p>

      <h2>How long we keep it</h2>
      <p>
        We retain enquiry and correspondence records only for as long as
        necessary to handle your enquiry, maintain accurate business records,
        and meet any legal or accounting obligations.
      </p>

      <h2>Your rights</h2>
      <p>
        Under UK GDPR, you have the right to request access to, correction
        of, or deletion of your personal data, to object to or restrict its
        processing, and to request a copy of it in a portable format. To
        exercise any of these rights, contact us using the details below. You
        also have the right to complain to the Information Commissioner&apos;s
        Office (ico.org.uk) if you believe your data has been mishandled.
      </p>

      <h2>Changes to this policy</h2>
      <p>
        We may update this policy from time to time. The date at the top of
        this page shows when it was last revised.
      </p>

      <h2>Contact us</h2>
      <p>
        For any question about this policy or your data, contact{" "}
        <a href="mailto:alan@apkindustries.com">alan@apkindustries.com</a>, or
        write to us at APK Industries Ltd, Sparkhouse, Rope Walk, Lincoln LN6
        7DQ, United Kingdom.
      </p>
    </LegalLayout>
  );
}
